### ISSUE TITLE
Unable to use scrollToItem

### ISSUE THREAD

**Issue by Viscmad** [filletofish/CardsLayout#4]
Unable to use scrollToItem it just keeps showing the current item.

**Comment by mkchoi212** [comment]
I'm having the same issue!

**Comment by lurein** [comment]
Did either of you manage to resolve this issue? I'm having the same one.
@Viscmad @mkchoi212 
Thanks,
-LP

**Comment by lurein** [comment]
@filletofish any response or workaround to this issue?

**Comment by filletofish** [comment]
Hi,

**Comment by filletofish** [comment]
Hi,

I have looked into the issue. The reason why `scrollToItem` was not working is because it scrolls until the required item is visible. The item can be visible (with very low alpha), but at the same time being the last item of collection view, not at the top of it.

The workaround I suggest is setting content offset. You can use the approach I am providing in snippet below:
```swift
extension UICollectionView {
  func scrollToItemInCardsLayout(item: Int, animated: Bool) {
    let contentOffset = CGPoint(x: self.bounds.width * CGFloat(item), y: 0)
    self.setContentOffset(contentOffset, animated: animated)
  }
} 
```

What do you think? @lurein @Viscmad  @mkchoi212
